title: ProdIsMyDev
email: chris@casualcompany.de
url: https://github.com/ProdIsMyDev/ProdIsMyDev
description: "Christoph Koenning - Developer from Hamburg, Germany. I like to build cool stuff and also stream sometimes."
keywords: "Christoph, Koenning, Stream, IT, Coding, CasualCompany, Developer, Development, Code, CS, ComputerScience"
skills: "Full Stack Developer - ML & DL Enthusiast"
meta_author: Koenning Christoph

contact: static

color:
  primary: 18bc9c
  primary-rgb: "24,288,156"
  secondary: 2c3e50
  secondary-dark: 233140

footer:
  copyright: Christoph Koenning
  location: Location
  social: Around the web
  credits: ProdIsMyDev

address:
  - line: Hamburg, Germany

social:
  - title: twitter
    url: https://twitter.com/ProdIsMyDev
  - title: github
    url: https://github.com/ProdIsMyDev
  - title: linkedin
    url: http://linkedin.com/in/christoph-koenning

credits: You have an interesting business proposal? <br>Feel free to get in contact with me!

markdown: kramdown
permalink: pretty
