title: "CV - Christoph Koenning"
description: ""

markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

resume_avatar: "true"
resume_name: "Christoph Koenning"
resume_title: "Software Engineer"
resume_contact_email: "chris@casualcompany.de"
resume_header_intro: "<p>I am a Full Stack Developer / Consultant, that loves to learn new things. If you are interested into my work, check out my <a style='color: inherit;' href='https://github.com/ProdIsMyDev'>GitHub</a> or follow me on <a style='color: inherit;' href='https://twitch.tv/ProdIsMyDev'>twitch.tv</a>, where I stream most of my work.</p>"
resume_looking_for_work: "no"

resume_section_experience: true
resume_section_education: true
resume_section_projects: true
resume_section_skills: true
resume_section_interests: true

resume_social_links:
  resume_github_url: "https://github.com/ProdIsMyDev"
  resume_twitter_url: "http://twitter.com/ProdIsMyDev"
  resume_linkedin_url: "https://www.linkedin.com/in/christoph-koenning/"
  resume_website_url: "https://ProdIsMy.dev"
  resume_medium_url: "https://medium.com/@ProdIsMyDev"
resume_print_social_links: true

resume_theme: default
