name: Build And Deploy Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: beta    
    - run: flutter config --enable-web
    - run: flutter pub get
    - run: flutter test
    - run: flutter build web

    - name: Deploy Application
        run: |
            cd build/web/
            echo 'prodismy.dev' > CNAME
            git init 
            git add -A
            git commit -m 'Automatic Deployment'
            git push -f https://${GH_PERSONAL_ACCESS_TOKEN}@github.com/$GITHUB_REPOSITORY.git gh-pages

