name: Build And Deploy Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: beta    
    - run: flutter config --enable-web
    - run: flutter pub get
    - run: flutter test
    - run: flutter build web

    - name: Deploy Application
      env:
        access_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      run: |
          cd build/web/
          echo 'prodismy.dev' > CNAME
          git init 
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit -m 'Automatic Deployment'
          git push origin -f https://prodismydev:$access_token@github.com/$GITHUB_REPOSITORY.git --branch=gh-pages gh-pages

